language: python

python:
 - "3.6"

env:
  - EXAMPLE=pydeep
  - EXAMPLE=terasort

sudo: required

services: docker

before_install: pip install flake8

# skip installation, requirements are handled in the Docker image
install: true

before_script:
  - flake8 -v .

script:
 - docker build --build-arg HADOOP_MAJOR_VERSION=3 -t crs4/pydoop-examples .
 - docker run --rm --name pydoop -d crs4/pydoop-examples
 - "docker exec pydoop bash -c 'while : ; do jps | grep DataNode && break; done'"
 - DEBUG=1 ./.travis/check ${EXAMPLE}
 - docker stop pydoop
